#+latex_header: \newcommand\bigO[1]{\mathcal{O}\left(#1\right)}
#+html_head: \( \newcommand\bigO[1]{\mathcal{O}\left(#1\right)} \)
#+title: Affine Cipher

* Helper functions
** ~ac--coprimep~
The equation for the affine cipher is \[ E(x) = (ai + b) \mod m \] where $a$
and $m$ must be [[https://en.wikipedia.org/wiki/Coprime_integers][coprime]]. It looks like the easiest way to determine if they are
is to implement the [[https://www.khanacademy.org/computing/computer-science/cryptography/modarithmetic/a/the-euclidean-algorithm][Euclidean GCD algorithm]], so let's write a function that
calculates that, and if it's 1, the numbers are coprime.

* Debugging
Having an issue extracting values from keys.

#+begin_src emacs-lisp
  ELISP> (alist-get "a" '(("a" . 6) ("b" . 17)))
  nil
  ELISP> (alist-get :foo '((:foo . 6) (:bar . 17)))
  6 (#o6, #x6, ?\C-f)
#+end_src

which is a problem for

#+begin_src emacs-lisp
  (defun encode (phrase key)
    (let ((a (alist-get "a" key))
          (b (alist-get "b" key))
          (m 26))
      (print (format (concat "a: %s\tm: %s\n"
                             "wholenums?: %s")
                     a m (and (wholenump a) (wholenump m))))
      (unless (ac--coprimep a m)
        (print (format "a: %s\tm: %s" a m))
        (error "a and m must be coprime."))
      (defun encode-char (c)
        (let* ((lowercase (number-sequence ?a ?z))
               (uppercase (number-sequence ?A ?Z))
               (letters (append uppercase lowercase)))
          ))))
#+end_src

Ohh.

#+begin_src emacs-lisp
  ELISP> (alist-get "a" '(("a" . 6) ("b" . 17)) nil nil #'string=)
  6 (#o6, #x6, ?\C-f)
#+end_src

That's kind of annoying.

* Refactoring
I implemented the modular multiplicative inverse function in the lazy/naïve
way.

#+begin_src emacs-lisp
  (defun ac--mmi (a m)
    "Return the modular multiplicative inverse X such that
  (`=' 1 (`mod' (`*' A X) M)) is t."
    ;; ultra-naive implementation -- do this the right way with extended
    ;; Euclidean GCD algorithm
    (let ((xs (number-sequence 2 (1- m))))
      (car-safe (seq-filter #'(lambda (x) (= 1 (mod (* a x) m))) xs))))
#+end_src

This is $\bigO{m}$, but the [[https://www.geeksforgeeks.org/euclidean-algorithms-basic-and-extended/][extended Euclidean algorithm]] is $\bigO{\log
m}$[fn::Of course, $m=26$ in this case, so it's never going to take /that/ long
to run, and it's going to take more of my time to do this the right way, +but I
might as well do it+.]

* Things I learned about from community solutions
There's a function, ~apply-partially~, that does exactly what it sounds like:
allows for partial function application.
